version: '3.9'

services:
  db:
    image: mysql:5.7
    ports:
    - "3306:3306"
    volumes:
    - db:/var/lib/mysql
    restart: always
    environment:
    - MYSQL_ROOT_PASSWORD=1111
    - MYSQL_DATABASE=jpastart
    networks:
    - board

  board:
    depends_on:
    - db
    build: .
    ports:
    - "8080:8080"
    networks:
    - board

volumes:
  db: {}

networks:
  board: {}